### PR TITLE
Update ioscross build to only run on develop branch

### PR DESCRIPTION
**Pull request by nonameentername**

### CODE REVIEW

**Comment by vlazzarini** [comment]
Should we enable the skipped tests to make sure they run OK before merging? That is to avoid having a failed build on develop and a red badge.

**Comment by vlazzarini** [comment]
We may not need this PR as I can see now that all builds went ahead on develop as I merged an other PR.

**Comment by nonameentername** [comment]
@vlazzarini ok, I'm going to go ahead and close this pr.  Not sure why the variables are not being used when creating pr's, but are being used on merge to development branch.

**Comment by nonameentername** [comment]
> [!NOTE]  
> The variables are not being used when the pr is from a fork of the project.

In order for the variables to be populated the merge request needs to be from the same organization and not a fork.

**Comment by vlazzarini** [comment]
thanks for clarifying.

**Pull request closed without merging**
