### PR TITLE
Link plugins to csound

### PR DESCRIPTION
**Pull request by bramtayl**
Already tried this once but. I don't understand the problem given it passes tests. And this is necessary for #1758 and #1739.

### CODE REVIEW

**Comment by bramtayl** [comment]
In the future, it might be good to have `CSOUNDLIB_PRIVATE` or something that has all the private headers as public. Then `CSOUNDLIB`, the plugins, and the executables could link to that instead.

**Comment by stekyne** [comment]
I'm not sure really what's the right solution here. As the guys stated elsewhere, there shouldn't really be any linking done. Maybe this can be modelled in Cmake with an interface library or something? https://cmake.org/cmake/help/latest/command/add_library.html#id4 I'll need to read more tbh

**Comment by bramtayl** [comment]
Yeah I'm still trying to get it straight

**Comment by bramtayl** [comment]
This is interesting reading though I don't understand it: https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_LINK_LIBRARIES_DIRECT.html

**Comment by bramtayl** [comment]
Ok, I think I understand better what's going on...some of the plugins use internal csound stuff that's not available in the public headers.

**Pull request closed without merging**
