### PR TITLE
printf: add the possibility to always print by setting the trigger to -1

### PR DESCRIPTION
**Pull request by gesellkammer**
When using printf inside an if clause it would be convenient to always execute the printing

```csound
if kval == 1 then
  ; code here
  printf "k1: %f\n", timeinstk(), k1
endif
```
With this PR, setting the trigger to -1 forces printf to print

```csound
if kval == 1 then
  ; code here
  printf "k1: %f\n", -1, k1
endif
```

### CODE REVIEW

**Comment by kunstmusik** [comment]
I think this breaks backwards compatibility as -1 could be a valid trigger value.  I'm not sure what use the trigger has personally. Perhaps an additional set of opcodes would be useful.  printfk could be a good name for one that removes trigger, for example.

**Comment by gesellkammer** [comment]
I created a new opcode, "echo", similar to printf, but without trigger. It runs at k-time and runs every at every cycle. Other than printf, in normal situations echo only ever allocates memory at init time and reuses that memory from previous instances. After having inspected the code, opcodes like printf should be documented as not realtime safe.

**Comment by kunstmusik** [comment]
Nice find regarding the memory allocation. Regarding echo, I'm a little worried that we have printf, printf_i, prints, printks, and now a new opcode name.  There's also puts as related opcode. I typically think of echo as just taking a string from bash scripting, rather than a formatted string. Also, I just realized printks with itime 0 prints every k-cycle.

**Comment by gesellkammer** [comment]
printks is not a solution. Try it with this .csd

```csound
<CsoundSynthesizer>
<CsOptions>

</CsOptions>

<CsInstruments>
sr     = 44100
ksmps  = 64
nchnls = 2
0dbfs  = 1

instr 1
    kidx = 0
    while kidx < 100 do
        if kidx % 2 == 0 then
            printks "kidx: %d", 0, kidx
        endif
        kidx += 1
    od
    turnoff
endin

instr 2
    S1 = "abcdefghijklmnopqrstuzwxyz"
    kidx = 0
    while kidx < 100 do
        k1 = kidx / 100
        S2 = sprintfk(">>>>>>>>>>>>> %d <<<<<<<<<<<<<<<", kidx * 1000000)
        printks "0123456789 0123456789 0123456789 %s :: %s :: %s %.10f %f %.16f\n", 0.0000001, S1, S2, S1, k1, k1, k1
        kidx += 1
    od
endin

</CsInstruments>

<CsScore>

i1 0 0.1
i1 + 0.1
;i2 0 0.1
;i2 + 0.1
;i2 + 0.1
; f0 3600

</CsScore>
</CsoundSynthesizer>


```

**Comment by gesellkammer** [comment]
But I am of course open to another name.

**Comment by gesellkammer** [comment]
Would "println" be better? Derived from the fact that this opcodes prints a new line by default (can be disabled if the format string ends in a comma).

**Comment by joachimheintz** [comment]
sorry for chiming in: println is a good name, in my opinion.

**Comment by gesellkammer** [comment]
Ok: I renamed it to "println". Manual page is ready too, so I can do a PR to the manual once this is merged.

**Comment by jpffitch** [comment]
Build FAILED.
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->

"C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj.metaproj" 
(default target) (20) ->
        "C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj" 
(default target) (92) ->
        (ClCompile target) ->
          C:\projects\csound\Opcodes\pinker.c(65,64): warning C4305: 
'initializing': truncation from 'double' to 'const float' 
[C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj]
          C:\projects\csound\Opcodes\pinker.c(68,64): warning C4305: 
'initializing': truncation from 'double' to 'const float' 
[C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj]
          C:\projects\csound\Opcodes\socksend.c(424,9): warning C4133: 
'function': incompatible types - from 'double *' to 'const char *' 
[C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj]
          C:\projects\csound\Opcodes\sockrecv.c(525,24): warning C4133: 
'function': incompatible types - from 'double *' to 'char *' 
[C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj]
          C:\projects\csound\Engine\cs_new_dispatch.c(351,13): warning 
C4133: 'function': incompatible types - from 'volatile state *' to 
'volatile LONG *' 
[C:\projects\csound\msvc\csound-vs\csound64-static.vcxproj]
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->
        "C:\projects\csound\msvc\csound-vs\csound64.vcxproj.metaproj" 
(default target) (19) ->
        "C:\projects\csound\msvc\csound-vs\csound64.vcxproj" (default 
target) (91) ->
          C:\projects\csound\Opcodes\pinker.c(65,64): warning C4305: 
'initializing': truncation from 'double' to 'const float' 
[C:\projects\csound\msvc\csound-vs\csound64.vcxproj]
          C:\projects\csound\Opcodes\pinker.c(68,64): warning C4305: 
'initializing': truncation from 'double' to 'const float' 
[C:\projects\csound\msvc\csound-vs\csound64.vcxproj]
          C:\projects\csound\Opcodes\socksend.c(424,9): warning C4133: 
'function': incompatible types - from 'double *' to 'const char *' 
[C:\projects\csound\msvc\csound-vs\csound64.vcxproj]
          C:\projects\csound\Opcodes\sockrecv.c(525,24): warning C4133: 
'function': incompatible types - from 'double *' to 'char *' 
[C:\projects\csound\msvc\csound-vs\csound64.vcxproj]
          C:\projects\csound\Engine\cs_new_dispatch.c(351,13): warning 
C4133: 'function': incompatible types - from 'volatile state *' to 
'volatile LONG *' [C:\projects\csound\msvc\csound-vs\csound64.vcxproj]
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->

"C:\projects\csound\msvc\csound-vs\interfaces\_jcsound6.vcxproj.metaproj" 
(default target) (4) ->
        "C:\projects\csound\msvc\csound-vs\interfaces\_jcsound6.vcxproj" 
(default target) (139) ->
        (CustomBuild target) ->
          C:\projects\csound\interfaces\CppSound.hpp(52): warning 813: 
Warning for CppSound, base CsoundFile ignored. Multiple inheritance is not 
supported in Java. 
[C:\projects\csound\msvc\csound-vs\interfaces\_jcsound6.vcxproj]
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->
        "C:\projects\csound\msvc\csound-vs\Opcodes\serial.vcxproj.metaproj" 
(default target) (70) ->
        "C:\projects\csound\msvc\csound-vs\Opcodes\serial.vcxproj" (default 
target) (152) ->
        (ClCompile target) ->
          C:\projects\csound\Opcodes\serial.c(354,52): warning C4311: 'type 
cast': pointer truncation from 'double *' to 'int32_t' 
[C:\projects\csound\msvc\csound-vs\Opcodes\serial.vcxproj]
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->

"C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj.metaproj" 
(default target) (71) ->
        "C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj" 
(default target) (153) ->
          C:\projects\csound\Opcodes\signalflowgraph.cpp(200,10): warning 
C4805: '==': unsafe mix of type 'int' and type 'bool' in operation 
[C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj]
          C:\projects\csound\Opcodes\signalflowgraph.cpp(206,1): warning 
C4805: '==': unsafe mix of type 'int' and type 'bool' in operation 
[C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj]
          C:\projects\csound\Opcodes\signalflowgraph.cpp(210,10): warning 
C4805: '==': unsafe mix of type 'int' and type 'bool' in operation 
[C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj]
          C:\projects\csound\Opcodes\signalflowgraph.cpp(211,1): warning 
C4805: '==': unsafe mix of type 'int' and type 'bool' in operation 
[C:\projects\csound\msvc\csound-vs\Opcodes\signalflowgraph.vcxproj]
        "C:\projects\csound\msvc\csound-vs\Csound.sln" (default target) (1) 
->

"C:\projects\csound\msvc\csound-vs\Opcodes\emugens\emugens.vcxproj.metaproj" 
(default target) (24) ->
        "C:\projects\csound\msvc\csound-vs\Opcodes\emugens\emugens.vcxproj" 
(default target) (94) ->
        (Link target) ->
          emugens.obj : error LNK2019: unresolved external symbol 
__imp_CS_VAR_TYPE_A referenced in function sprintf_opcode_ 
[C:\projects\csound\msvc\csound-vs\Opcodes\emugens\emugens.vcxproj]
          emugens.obj : error LNK2019: unresolved external symbol 
__imp_CS_VAR_TYPE_S referenced in function sprintf_opcode_ 
[C:\projects\csound\msvc\csound-vs\Opcodes\emugens\emugens.vcxproj]
          C:\projects\csound\msvc\csound-vs\Release\emugens.dll : fatal 
error LNK1120: 2 unresolved externals 
[C:\projects\csound\msvc\csound-vs\Opcodes\emugens\emugens.vcxproj]
     16 Warning(s)
     3 Error(s)
Time Elapsed 00:07:29.96
Command exited with code 1
APPVEYOR_SAVE_CACHE_ON_ERROR is set to 'true' - cache will be updated

**Comment by gesellkammer** [comment]
Any clue why this is failing in windows? The structures are declared in csound_standard_types.h which is included by csoundCore.h which is included in csdl.h.

**Comment by jpffitch** [comment]
I am not a Windows user but one thought was that some of the messages 
looked like C++ remarks, like reference to a bool type.

and the "external symbol __imp_CS_VAR_TYPE_A " looks like C++ name 
mangling

**Comment by gesellkammer** [comment]
Now it's github failing but this seems to be internal. Windows seems happy now. Linux and macOS build ok locally.

**Comment by kunstmusik** [comment]
I retriggered the Github build and it went through. I don't really understand why there's a special case here for the comma; seems a source for bugs and no obvious way to intentionally end a line with a comma. 

I think calling this println is also conflating two things together: printing with a new line automatically and doing formatted strings.  

My vote is for printfk as an opcode name.

**Comment by kunstmusik** [comment]
The comma in python is not a part of the string:

```python2
>>> def a():
...   print "a",
...   print " b"
... 
>>> a()
a  b
>>> def b():
...   print "a"
...   print " b"
... 
>>> b()
a
 b
```

So that doesn't really apply here. 

I obviously find printfk fine since I suggested it, but I also think the situation is already a big mess so it doesn't seem to harm.  Maybe better would be printsk (to be an analog to prints, just at k-rate).  

I'd be alright with println at this point but I do think the comma handling isn't justified.

**Comment by gesellkammer** [comment]
I like the idea of printsk. We could settle on that and remove the appended new line to make it even more homogeneous. A version with a new line appended could be added as "println", without the comma handling. Would that be ok?

**Comment by kunstmusik** [comment]
Yes, that sounds great to me, thanks!

**Comment by kunstmusik** [comment]
@gesellkammer This PR still looks like it has the -1 change for printf.  Could you revert that change?

**Comment by kunstmusik** [comment]
All looks good and testing here worked as expected. Thanks!

**Comment by jpffitch** [comment]
What about the error printer?  That needs fixing.

⁣Sent from TypeApp ​

**Comment by gesellkammer** [comment]
What do you mean with "error printer"?

**Comment by jpffitch** [comment]
Errormsg

**Comment by gesellkammer** [comment]
That PR was withdrawn, since the proposed fix by @jpffitch could not be accomplished in plugin code.

**Comment by jpffitch** [comment]
It was in the commit log which was why I raised it.

⁣Sent from TypeApp ​

**Pull request merged**
