### PR TITLE
Remove duplicate Windows csound64.lib creation script

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request removes mingw64/make_import_library_32.cmd (mentioned [here](https://github.com/csound/csound/issues/720#issuecomment-265945302)), and it lets mingw64/make_import_library.cmd also create a 32-bit csound64.lib by running

```batch
make_import_library /machine:x86
```

This pull request also fixes various issues in mingw64/README.md so that, for example, numbered lists increment properly when displayed on GitHub.

I should note that there’s still another csound64.lib creation script at https://github.com/csound/csound/blob/develop/make_import_library.cmd. I’m not sure why it’s there, or whether it can be removed.

### CODE REVIEW

**Comment by nwhetsell** [comment]
By the way, passing `/machine:x86` to this script makes use of [the fact that](https://msdn.microsoft.com/en-us/library/h34w59b3.aspx):

> LIB processes options in the order specified on the command line and in command files. If an option is repeated with different arguments, the last one to be processed takes precedence.

**Comment by kunstmusik** [comment]
@rorywalsh @gogins  This looks like something for you all to review?

**Comment by gogins** [comment]
Looks good to me.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by rorywalsh** [comment]
Me too.

**Pull request merged**
