### PR TITLE
Switch unit test framework to Google Test

### PR DESCRIPTION
**Pull request by stekyne**
First set of changes to get this going. It is compiling but having a runtime issue. Not sure yet why, so this shouldn't be pulled just yet.

Changes so far:
Convert unit tests to cpp files, framework has to be compiled as C++. This meant some other changes with regards to imports from C code.
Changed the API usage to GTest, it's similar enough to what CUnit provided but has more features.
Updated the CMakeLists.txt to find the GTest package.

Still to do:
Update VCPKG package build to download GTest (easy)
Update Travis CI to appget GTest (I assume)
Solve the runtime issue. There is a invalid heap access in GTest on loading the first test. Seems to be related to the way Csound is being linked.
Verify the unit tests are working as expected.

Nice to do:
Add some benchmark tests
Add more unit test coverage
Update CI builds to run unit tests on every build

### CODE REVIEW

**Comment by jpffitch** [comment]
Is this wise just before a release?  Still not happy with more c++.

⁣Sent from TypeApp ​

**Comment by vlazzarini** [comment]
It should be done on a branch for the moment.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

On 18 Dec 2017, at 12:28, John ffitch <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this wise just before a release?  Still not happy with more c++.

⁣Sent from TypeApp ​

**Comment by stekyne** [comment]
It's probably best to leave it's inclusion until after the release. It's on it's own google test feature branch for now anyway.

I don't see the issue with using C++? Google Test is the most feature rich framework and it seems like a lot of C projects use it for testing anyway. More generally, I think C++ makes the most sense when writing a cross-platform project that includes Windows. At best, we have C99 (partially) as a standard across the major platforms. With C++, MSVC/Clang/GCC all support  C++17 (nearly complete). We would have avoided any messiness with pthreads and atomics by using std::atomic plus std::thread. Not too mention all of the STL and various other language features (templates, smart pointers etc).

Anyway, that's a tangent from what this PR is about. I'll leave this open for more discussion about what to do.

**Comment by fsateler** [comment]
The relevant package for travis is `libgtest-dev` (newer debian/ubuntu versions need `googletest`, but travis is a bit slow to update).

**Comment by vlazzarini** [comment]
The checks need to be fixed before we can accept this on the branch.

**Comment by jpffitch** [comment]
Because C++ is a language that encourages bad practice and makes code opaque. Precisely templates etc

**Comment by kunstmusik** [comment]
I'm interested in unit tests being taken more seriously as part of our development process.  As it is now, I've little to no tests--C or Csound CSD--committed in a very long while. If we don't really use unit tests as part of our development, it doesn't really make any difference whatsoever if we use C or C++. 

If using GTest is going to be easier to get setup than CUnit and promotes more unit testing, then I'm all for it. Granted, I also prefer less C++ in general, but here it seems more plus than minus to go with GTest.

**Comment by jpffitch** [comment]
I have a number of fixed bug*.csd files which could be added to 
regression, but I am not confident with python as used in the driver.
I may try when I have time

**Comment by vlazzarini** [comment]
yes I am very happy with more testing.

**Comment by kunstmusik** [comment]
@jpffitch I wrote the python test scripts ages ago as something to get the process going. If there's something else that'd work better for you and that we can get to work cross-platform, then happy to switch.

**Comment by gogins** [comment]
Gentlemen and friends, I cannot allow your subjective and incorrect
comments about C++ to stand.

I have extensive, paid, professional experience writing applications and
systems in C, C++, Java, C#, and Python. In addition to this now four
decades of experience, I have maintained a watch over programming
languages, what they can do, what they are actually used for, and how fast
they are. I care very much which languages are best for my purposes, but I
have no personal stake in the answer, and I have switched my main
programming languages several times as languages and tools have evolved. I
would switch again if I found that a better language had appeared. I would
switch to C, which I know well, if I found it superior to C++.

I will start by admitting that C++ is indeed quite complex. However, it is
not necessary to use the complexities of C++ to write fast, easy to read
code. In addition, the complexities allow the language to be "tuned" and
used for an extremely wide variety of applications.

Your GNU C compiler itself is written in C++. The Microsoft compiler is
written in C++. The clang compiler is written in C++. The OpenJDK (Oracle)
Java runtime is written in C++. The JavaScript runtime in Google Chrome is
written in C++. The JavaScript runtime in Mozilla Firefox is written in C++.

Currently, Google uses C++ for all critical software. Both Microsoft Office
and Libre Office are almost completely written in C++. Some avionics
software is written in C++. A quarter or so of automotive, medical, and
electronics embedded software is written in C++.

Almost all computer games and almost all commercial music and audio
applications are written in C++. Finale, Sibelius, and MuseScore are
written in C++. I believe Ableton Live is written in C++. Reason is written
in C++.

About half of both open source and commercial database servers, both SQL
and large file based, are written in C++. At least two of the top machine
learning software frameworks are largely written in C++ (TensorFlow, Caffe).

Windows is written mostly in C++, bits of OS X are written in C++. iOS is
written partly in C++, Android is written partly in C++.

Oh yes, of the major GUI framework SDKs, most are written in C++: Qt, MFC,
ATL, Juce, FLTK, KDE, wxWidgets.

Repeated tests by many people including myself have demonstrated that,
without descending to writing very labor intensive assembler, it is not
possible to write faster programs than by using C++. It certainly can't be
done in C. You might be able to do it with a JITted language.

A number of projects migrated to Java in the 1990s, and then to C++
(OpenOffice was one).

Experience by automotive, avionics, and embedded developers has found ways
of writing safe, bug-free, easy to maintain code in any language. These
principles have been applied in detail to C++.

I don't mind you guys preferring C to C++ for whatever reason, but please.
Obviously it is possible to write easy to read, bug-free code in C++ on any
platform.

Best,
Mike




-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
I find it hard to read these comments to use C++ over so many years when so much of Csound's instabilities/crashes I have seen in that same time has come from C++ code (your opcodes in particular). I actually find modern C++ interesting and I see lots of interesting projects in C++ (some of the very ones you've mentioned). Yet, try as I might, because of so many negative experiences with C++ in Csound's codebase to date, I find I have little interest to use or promote it in Csound unless there's a good reason (such as here for GTest).

**Comment by jpffitch** [comment]
I looked at the test.py program and it seems that just adding to a table is 
all that is required to extend the tests. I did a couple yesterday late 
(not committed) and hope to add more.  Only concern is that it a test for 
error/no-error and not for the actual output.  Anyway I will add ex-bug 
cases as appropriate.

**Comment by kunstmusik** [comment]
Sounds good, we can maybe open up a separate issue for updating the CSD
tests runner.

**Comment by stekyne** [comment]
Just to update, after some discussion it was decided that GTest is too heavyweight and C++ orientated to include in Csound. Therefore I'm going to switch to a C library preferably lightweight or header only. There are a few libraries that seem to be maintained and in use these days.

https://github.com/Snaipe/Criterion
https://libcheck.github.io/check/
https://cmocka.org/
http://www.throwtheswitch.org/unity

They all seem to have a decent and friendly API.  What will probably decide it is how easy it is to integrate and if there is a package available for each platform.

**Comment by kunstmusik** [comment]
If it's header only, we could easily add to our project or pull in via
gitmodule or other means.

**Comment by stekyne** [comment]
Any reason this was deleted?

**Comment by kunstmusik** [comment]
Any reason this was closed?

**Comment by stekyne** [comment]
Closed it for now seeing as there hasn't been much progress. It's a lot of work to change all of this again. I've only really found C++ testing frameworks. Catch, doctest, gtest etc. Unless there was some agreement that it's alright to introduce more C++ then I'm hesitant to spend the time making the changes. I do think it would be a big benefit. Particularly in testing the parser etc.

**Comment by kunstmusik** [comment]
I'm all for C++ for the unit tests.  @vlazzarini @jpff thoughts?

**Pull request closed without merging**
