### PR TITLE
Add python option

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Closes #1728

**Comment by kunstmusik** [comment]
FYI: We typically don't do PRs directly to master branch. If for CS6 we generally expect it to target the csound6 branch; otherwise develop for csound 7. 

Are these changes expected to be a hotfix to the master?

**Comment by bramtayl** [comment]
Whatever you think is best

**Comment by bramtayl** [comment]
Close in favor of #1735

**Pull request closed without merging**
