### PR TITLE
Add portmidi module

### PR DESCRIPTION
**Pull request by bramtayl**
Using imported targets has several benefits:

- Packaging include-dirs and libraries together for cleaner code
- Automatic handling of usage requirements (see https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#target-usage-requirements)
- Tracking of runtime dependencies (https://cmake.org/cmake/help/latest/command/install.html#runtime-dependency-set)
- Unifies vcpkg and non-vcpkg builds

### CODE REVIEW

**Comment by stekyne** [comment]
This should probably be tested on Mac as well to be sure

**Comment by bramtayl** [comment]
Why isn't there CI on Mac?

**Comment by stekyne** [comment]
It's just a bit more complicated. I was in the process of doing it but ran into some issues. I'll probably take a look again soon.

**Comment by bramtayl** [comment]
Part of #1811 now

**Pull request closed without merging**
