### PR TITLE
WIP: Port GCC builtins from __sync to __atomic

### LINKED ISSUE #977: testEngine hangs when atomic builtins are not used
As shown in the [debian build logs](https://buildd.debian.org/status/package.php?p=csound&suite=sid). This appears to be a regression in 6.11:

```
...
   debian/rules override_dh_auto_test
make[1]: Entering directory '/<<PKGBUILDDIR>>'
OPCODE6DIR64=obj-aarch64-linux-gnu dh_auto_test
        cd obj-aarch64-linux-gnu && LC_ALL=C.UTF-8 MESON_TESTTHREADS=3 ninja test
[0/1] Running tests...
Test project /<<PKGBUILDDIR>>/obj-aarch64-linux-gnu
      Start  1: testCsoundTypeSystem
 1/12 Test  #1: testCsoundTypeSystem .............   Passed    0.27 sec
      Start  2: testCsoundMessageBuffer
 2/12 Test  #2: testCsoundMessageBuffer ..........   Passed    0.09 sec
      Start  3: testCsoundOrcSemantics
 3/12 Test  #3: testCsoundOrcSemantics ...........   Passed    0.29 sec
      Start  4: testCsoundOrcCompileTest
 4/12 Test  #4: testCsoundOrcCompileTest .........   Passed    5.05 sec
      Start  5: testChannels
 5/12 Test  #5: testChannels .....................   Passed    0.33 sec
      Start  6: testCsoundDataStructures
 6/12 Test  #6: testCsoundDataStructures .........   Passed    0.03 sec
      Start  7: testIo
 7/12 Test  #7: testIo ...........................   Passed    0.73 sec
      Start  8: testCircularBuffer
 8/12 Test  #8: testCircularBuffer ...............   Passed    0.03 sec
      Start  9: testPerfThread
 9/12 Test  #9: testPerfThread ...................   Passed   13.07 sec
      Start 10: testDebugger
10/12 Test #10: testDebugger .....................   Passed    0.09 sec
      Start 11: testEngine
E: Build killed with signal TERM after 150 minutes of inactivity
```

### PR DESCRIPTION
**Pull request by fsateler**
GCC recommends use of these instead of the __sync primitives.

Enables use on platforms without atomic primitives by linking with
libatomic

Fixes #977 

Not sure if these atomics work with LLVM. Could the mac people comment if this works?

### CODE REVIEW

**Comment by vlazzarini** [comment]
I think this is ok with clang

https://llvm.org/docs/Atomics.html#libcalls-atomic

One question, which I am sure it is ok, but just checking, the fork you used for this PR does not have tainted commits, does it? I am just mindful of the fact that one of the commits that caused our
git history duplications came from a PR that we did not check for this.

**Comment by fsateler** [comment]
> One question, which I am sure it is ok, but just checking, the fork you used for this PR does not have tainted commits, does it? 

This PR is tainted. I was waiting for an official notification of the commit history edit before rebasing. I marked the PR as WIP to avoid merging until that is done.

**Comment by fsateler** [comment]
BTW, at least on linux clang compiles this and tests pass.

**Comment by vlazzarini** [comment]
yes, Travis shows it passes clang, so we're good. Thanks for this. I hope we can make the decision on how to do the history edit and complete it soon.

**Pull request closed without merging**
