### PR TITLE
Own ugens and initial port of some supercollider ugens

### PR DESCRIPTION
**Pull request by gesellkammer**
# emugens: Miscelaneous ugens for csound

## bpf

Breakpoint function (linear interpolation). Interpolates between the points (kxn, kyn).

    ky  bpf kx, kx0, ky0, kx1, ky1, kx2, ky2, ...

## linlin

Linear to linear conversion, similar to Supercollider's `linlin`.

Converts a value `x` defined within a range `kxlow - kxhigh` to the range
`kylow - kyhigh`

    ky  linlin kx, kxlow, kxhigh, kylow, kyhigh

## ftom, mtof

Frequency <--> Midi conversion. Uses csound's A4 global variable

    kfreq = mtof(69)

## ntom, mton

Notename to midi conversion. Format used: `4C[+15]`

* Octave + notename. `4C`, `5Db`, `3A#`, etc
* `4C` is the central C on the piano
* Cents can be indicated as `4C+15` (15 cents higher), `4C-31` (31
cents lower)
* `4C+` is also accepted, and is the same as `4C+50` (the same is
valid for `4C-`
* Only uppercase is accepted

## pchtom

Convert octave.pitch to midi

    kmidi = pchtom(8.07)

## xyscale

2D interpolation between 4 presets, like a xy widget

    kout  xyscale kx, ky, k00, k10, k01, k11
 

Given 4 values corresponding to points at

    k10          k11

    k00          k10

interpolate the values according to kx, ky, 
where kx and ky are between 0-1

This is the same as:

    ky0 = scale(kx, k01, k00)
    ky1 = scale(ky, k11, k10)
    kout = scale(ky, ky1, ky0)

# scugens. Some supercollider ugens ported to csound

## Lag

This is essentially the same as OnePole except that instead of
supplying the coefficient directly, it is calculated from a 60 dB lag
time.
This is the time required for the filter to converge to within 0.01% 
of a value. This is useful for smoothing out control signals.

krate and arate

    ksmooth = lag(kx, klagtime, [initialvalue=0])
    asmooth = lag(ka, klagtime, [initialvalue=0])

## LagUD

The same as Lag but with different lag times for up and down slope

    ksmooth = lagud(kx, klagup, klagdown, [i0=0])
    asmooth = lagud(ax, klagup, klagdown, [i0=0])

## Phasor

A resettable phasor

	aindex = phasor(atrig, xrate, kstart, kend, [kresetpos=0])
	kindex = phasor(ktrig, krate, kstart, kend, [kresetpos=0])

## Trig

Hold a trigger for a given duration
    
    xheldtrig = trig(xvalue, kdur)

    ktrig = trig(metro(2), 0.1)
    atrig = trig(avalue, kdur)

### CODE REVIEW

**Comment by vlazzarini** [comment]
The travis check has failed, could you fix this and then re-commit?

**Comment by gesellkammer** [comment]
fixed, do I need to redo the PR?

**Comment by vlazzarini** [comment]
Thanks.

**Comment by vlazzarini** [comment]
Hi Eduardo, could you do a pull request for the manual with the new opcode manual pages?

**Comment by gesellkammer** [comment]
I was just looking into this. What is the preferred tool for writing the docbooc xml?

**Comment by vlazzarini** [comment]
I just use a text editor (emacs).

**Comment by jpffitch** [comment]
And note there is a template in the manual tree for an opcode page.⁣

**Comment by jpffitch** [comment]
Also is it OK if I add the normal Csound licence (LGPL)?
==John ffitch

**Comment by jpffitch** [comment]
Also these opcodes do not check arguments to stop division by zero.  I have marked one case but there are many

**Comment by vlazzarini** [comment]
I am getting a fair number of warnings:

```
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:44:18: warning: using integer absolute value function 'abs' when
      argument is of floating point type [-Wabsolute-value]
    MYFLT absx = abs(x);
                 ^
/Users/victor/src/csound6/Opcodes/emugens/emugens.c:84:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:44:18: note: use function 'fabs' instead
    MYFLT absx = abs(x);
                 ^~~
                 fabs
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:134:14: warning: unused variable 'n' [-Wunused-variable]
    uint32_t n, nsmps = CS_KSMPS;
             ^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:224:14: warning: unused variable 'nsmps' [-Wunused-variable]
    uint32_t nsmps = CS_KSMPS;
             ^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:340:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:384:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:390:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/emugens.c:390:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
2 warnings generated.
6 warnings generated.
/Users/victor/src/csound6/Opcodes/emugens/emugens.c:84:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/emugens.c:390:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:44:18: warning: using integer absolute value function 'abs' when
      argument is of floating point type [-Wabsolute-value]
    MYFLT absx = abs(x);
                 ^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:44:18: note: use function 'fabs' instead
    MYFLT absx = abs(x);
                 ^~~
                 fabs
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:134:14: warning: unused variable 'n' [-Wunused-variable]
    uint32_t n, nsmps = CS_KSMPS;
             ^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:224:14: warning: unused variable 'nsmps' [-Wunused-variable]
    uint32_t nsmps = CS_KSMPS;
             ^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:340:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:384:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
^
/Users/victor/src/csound6/Opcodes/emugens/scugens.c:390:1: warning: control reaches end of non-void function
      [-Wreturn-type]
}
```

**Pull request merged**
