### PR TITLE
Hotfix/boolcrash

### PR DESCRIPTION
**Pull request by vlazzarini**
This PR addresses a crash when a boolean expression is expected but not present, for example as described in #1669. This crash happens on other statements (if, while etc) expecting a boolean expression.

### CODE REVIEW

**Comment by kunstmusik** [comment]
Could you add a csd test for this? I don't know what to test here.

**Comment by vlazzarini** [comment]
Here's the code given in the issue
```
<CsoundSynthesizer>
<CsInstruments>
sr=44100
ksmps=1
nchnls=1


instr 1
  ix = 0
  bi = ix == 10
  until bi do
   ix += 1
  od
endin


</CsInstruments>
<CsScore>
i1 0 0
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by kunstmusik** [comment]
Note this has a different approach than https://github.com/csound/csound/pull/1672/. I want to look at both to see what's a good path forward on this.

**Comment by vlazzarini** [comment]
it's probably a more thorough fix than mine.

**Comment by vlazzarini** [comment]
I'm wondering about this one. The segfault still happens. It would be good to fix it in some way, even if temporary.

**Comment by vlazzarini** [comment]
Closed this in favour of https://github.com/csound/csound/pull/1672.

**Pull request closed without merging**
