### PR TITLE
add offset index to copya2ftab

### PR DESCRIPTION
**Pull request by gesellkammer**
With this PR it is possible to determine an offset into the ftable when copying from an array (the offset defaults to 0). 

`copya2ftab` will copy the elements of the array into the ftable starting at the given offset.

I can send a PR for the manual documenting this change.

### CODE REVIEW

**Comment by gesellkammer** [comment]
New opcodes added:
* lastcycle: returns 1 if this is the last performance-cycle of the event
* strstrip: strip whitespace from string, either from left, right or both sides

**Comment by jpffitch** [comment]
Do you have manual pages for the new opcodes?

Would it not be easier to make the index optional defaulting to zero?

**Comment by jpffitch** [comment]
If a negative offset is specified your code reads outside the array i think.  Surely this should be policed.

**Comment by gesellkammer** [comment]
* copya2ftab checks for negative index
* now index optional (default 0) in copya2ftab

**Comment by jpffitch** [comment]
Thank you.  Will deal with it soon.

⁣Sent from TypeApp ​

**Pull request merged**
