### PR TITLE
Module['print'] no longer available

### PR DESCRIPTION
**Pull request by hfmanson**
Module['print'] is no longer available in CsoundObj.js and all references should be removed

### CODE REVIEW

**Comment by kunstmusik** [comment]
I'm wondering about having messages with console.log(), but I don't know if that's useful or not since for these two scenarios both have success/fail callbacks. @vlazzarini any thoughts?

**Comment by vlazzarini** [comment]
Not sure. I thought 'print' was still available for the SPN case.

**Comment by hfmanson** [comment]
I think it would be best to export a function CsoundObj_message in CsoundObj,c which encapsulates csoundMessage and add a wrapper to CsoundProcessor.js and CsoundScriptProcessorNode.js called 'message'

**Comment by hfmanson** [comment]
You can replace Module['print'] with console.log. console.log will display in the csound console window when used after moduleDidLoad
<pre>
function moduleDidLoad() {
   csound.Csound.enableMidiInput(undefined);
   ...
}
</pre>

**Comment by kunstmusik** [comment]
@hfmanson Using console.log seems good to me, but not sure how removing enableMidiInput() is necessary?  Could you explain what moving that to moduleDidLoad does?

**Comment by hfmanson** [comment]
Now the webpage using csound should enable MIDI itself through csound.Csound.enableMidiInput(undefined); in moduleDidLoad. The advantage is, when MIDI is not supported by the browser, an error message will display in the csound console window

**Comment by kunstmusik** [comment]
Going to merge as the change makes sense to me. (@vlazzarini may want to review and modify csound.js though.)

**Pull request merged**
