### PR TITLE
Changes to allow compiling for Android using vcpkg

### PR DESCRIPTION
**Pull request by nonameentername**
Implementation for #1843

### CODE REVIEW

**Comment by stekyne** [comment]
@kunstmusik do you know who uses/maintains the android build?

**Comment by kunstmusik** [comment]
I think @rorywalsh is maintaining Android now.

**Comment by rorywalsh** [comment]
It's true, I put my hand up a some point. This PR looks good to me, but I've no experience with docker images.

**Review by rorywalsh — COMMENTED** [review]
I've gone over this and it looks good. I can't accept PRs, Stephen/Steven do you guys have any concerns about this?

**Comment by stekyne** [comment]
It looks ok to me but it's disabled in the CI. We need to run it at least once to make sure it's all good

**Comment by nonameentername** [comment]
In this PR, there are two new jobs for the CI/CD pipeline:

Docker Image Creation Job:
- This job builds a Docker image.
- It saves the Docker image as an artifact.
- It stores the workflow run ID for future reference.

Android CI Job:
- This job uses the stored workflow run ID to download the Docker image artifact.
- It then executes the build process.

To enable Android CI:
- Manually run the Docker build job.
- Create a variable in the CI settings named ANDROID_WORKFLOW_RUN_ID, and set its value to the workflow run ID of the Docker image build job.

Additional Configuration:

- I have added functionality to automatically set the workflow run ID when building the Docker images.
- To use this feature, a fine-grained access token is required with the following permissions:
 1. Read access to metadata
 2. Read and Write access to actions variables
- Once the token is created, it can be added as a secret named SERVICE_ACCOUNT_PAT.

**Comment by stekyne** [comment]
Ok lets see how it works out maybe. It sounds pretty well reasoned.

**Review by stekyne — APPROVED** [review]

**Pull request merged**
