### PR TITLE
added static building for opcodes to resolve csound tilde issue on windo...

### PR DESCRIPTION
**Pull request by rorywalsh**
...ws

This doesn't seem to be necessary on any other platforms and leads to larger plugin library sizes, but so far it's the only thing I could do to get csound~ to load. 

csound~ needs be modified so that it enforces -+rtaudio=null

### CODE REVIEW

**Comment by vlazzarini** [comment]
The thing to do is to protect it so that it only affects Windows. Whoever accrpts this merge request should do that.

**Comment by vlazzarini** [comment]
Note that the linux build is failing too.

**Comment by rorywalsh** [comment]
I have had to comment out the building of padsynth to get it to build for me on Windows.

**Comment by kunstmusik** [comment]
I don't think we can use this patch; a change like that should be globally controlled I think. This could maybe be added to make_plugin in the main CMakeList.txt and isolated to windows.

**Comment by rorywalsh** [comment]
That sounds reasonable. Or rather than isolate this particular build setup to windows, perhaps we could simply enable a CMAKE build option for static linking to pthread and liibgcc?

**Pull request closed without merging**
