### PR TITLE
generic assign fix

### PR DESCRIPTION
**Pull request by vlazzarini**
This PR implements a fix to generic assign that allows init-time and perf-time copying according to variable types.

### CODE REVIEW

**Comment by kunstmusik** [comment]
This branch has a new failure with test_array_operations.csd. Looking at it now.

**Comment by kunstmusik** [comment]
@vlazzarini I made a change to always copy at init-time (https://github.com/csound/csound/pull/1928/commits/f8120f557bfbbef35f3523fb213dd95717c4efb7) This got the test to pass. I suspect this is fine, but wanted to double-check with you before merging this in.

**Comment by vlazzarini** [comment]
Ok, you know more about this than I do. I am not too familiar with the changes brought in by the introduction of =.generic. We'll need to keep an eye on this, John mentioned some issues with RTypes connected to this on the list. They may have been addressed though.

**Comment by kunstmusik** [comment]
I'll merge this in now then, thanks!

**Review by kunstmusik — APPROVED** [review]

**Pull request merged**
