### PR TITLE
Use threads module

### PR DESCRIPTION
**Pull request by bramtayl**
Use the built-in cmake threads module.

Using imported targets has several benefits:

- Packaging include-dirs and libraries together for cleaner code
- Automatic handling of usage requirements (see https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#target-usage-requirements)
- Tracking of runtime dependencies (https://cmake.org/cmake/help/latest/command/install.html#runtime-dependency-set)
- Unifies vcpkg and non-vcpkg builds (although threads isn't a vcpkg package)

### CODE REVIEW

**Comment by stekyne** [comment]
This does look pretty good. Is there anything that is risky about this change?

@kunstmusik what do you think?

**Comment by kunstmusik** [comment]
The code here looks good to me. Android and Web builds are broken at the moment but I would not expect them to be affected by this change.  

 @bramtayl: I don't understand the PR description and it looks like it's some copy/paste from another PR. Could you update the description to describe this PR's changes in case we have to look back at this ticket?
 
Once that's cleared up I think we're good to merge @stekyne.

**Comment by bramtayl** [comment]
Ok, updated, but the notes about using imported targets should mostly still apply here

**Comment by kunstmusik** [comment]
Merging, thanks for the contribution

**Pull request merged**
