### PR TITLE
AudioWorklet output channel fix + MIDI support

### PR DESCRIPTION
**Pull request by hfmanson**
In AudioWorkletNode each input and output can have multiple channels. The number of channels in an output is specified in options.outputChannelCount per output. In Csound we only have one output, which can contain multiple channels. Now my stereo tobias.csd works. 

Midi support fix

### CODE REVIEW

**Comment by kunstmusik** [comment]
@hfmanson The output channel fix makes sense to me, but could you explain the MIDI support change?  Just want to make sure I understand the change and that it is there to restore older built-in WebMIDI support to CsoundObj.js, yes?

**Comment by hfmanson** [comment]
I copied enableMidiInput(midiInputCallback) from a previous version of CsoundObj.js and modified it so the midiInputCallback parameter can be optional. When a MIDI event occurs on the main thread it is posted to the audioprocessor (ScriptProcessorNode or AudioWorklet) through the already present midiMessage function

**Comment by kunstmusik** [comment]
I tested a build with the changes and found that:

1. Stereo was indeed not working and is now fixed
2. MIDI input worked. I do not use csound.js so that change would best be reviewed by @vlazzarini. The addition of the enableMidiInput() method to CsoundObj looks good to me.  One can decide to use it if they want to, or they can do the WebMIDI code themselves and have finer control over how to handle MIDI devices.  

@vlazzarini - I think these changes are good.  If you're okay with the csound.js change, I will go ahead and merge and close.

**Comment by kunstmusik** [comment]
One note: we could use an arrow function so that we wouldn't have to use the "that", something like:

```javascript
        const handleMidiInput = (evt) => {
            this.midiMessage(evt.data[0], evt.data[1], evt.data[2]);
            //console.log("midievent: " + event.data[0] + ", " + event.data[1] + ", " + event.data[2]);
        };
```

**Comment by hfmanson** [comment]
@kunstmusik Just tested the arrow function. 'this' is undefined, it seems handleMidiInput is called on another MIDI thread

**Comment by kunstmusik** [comment]
@hfmanson Check out the code in context here:

https://github.com/kunstmusik/csound-audioworklet/blob/master/csound/CsoundObj.js#L311-L315

I get console output when driving this test page:

https://kunstmusik.github.io/csound-audioworklet/midiInputTest.html

with MIDI output.  The console.log shows:

CsoundObj.js:313 ƒ midiMessage(byte1, byte2, byte3) {
        this.node.midiMessage(byte1, byte2, byte3);
    }

**Comment by hfmanson** [comment]
I am afraid I got fooled by the debugger, now the arrow function works correctly. I'm ok with that change

**Comment by kunstmusik** [comment]
Merged. I will add the arrow function shortly. Thanks all!

**Pull request merged**
