### PR TITLE
Let syntax check return an error when failed

### PR DESCRIPTION
**Pull request by gesellkammer**
Trying this again, as it was prematurely closed. This PR is necessary in order to avoid csound crashing when in --daemon mode and the first compile fails. This crash brings down also any frontend (CsoundQt, ctcsound) with it. With this in place it is possible to preform a syntax check and see if it succeeded or not.

### CODE REVIEW

**Comment by vlazzarini** [comment]
Thanks. It seems to be bringing in a backup file into the repo. Can you check?

**Comment by jpffitch** [comment]
committed

**Comment by jpffitch** [comment]
istalled from a local copy to avoif d the half-editted fie

**Comment by vlazzarini** [comment]
Is this incorporated? Can it be closed.

**Comment by jpffitch** [comment]
Certainlt; I thought it was closed.

**Pull request closed without merging**
