### PR TITLE
Feature/oboe

### PR DESCRIPTION
**Pull request by gogins**
Please merge updates to the Csound for Android application, the CsoundAndroid library, and the Android build system for system.

The CsoundOboe class is based on the Google Oboe audio driver library for Android, and has semantics slightly more in line with csound.h and csound.hpp.

The CsoundObj and csound.js facilities remain unchanged, as do the Android example apps.

### CODE REVIEW

**Comment by vlazzarini** [comment]
This PR needs attention as noted in the original issue:
https://github.com/csound/csound/issues/887#issuecomment-357707338

Once that's resolved, I can test on MacOs as well.

**Comment by dturner** [comment]
(I am one of the authors of the Oboe library) Is someone able to resolve this merge conflict? Once support is added I would like to mention this on the Oboe github homepage.

**Comment by dturner** [comment]
Thanks Mike. I've added links to the CSound for Android app and source code to the [Oboe homepage](https://github.com/google/oboe/)

**Comment by gogins** [comment]
Thanks!

Mike

**Pull request closed without merging**
