### PR TITLE
WASM AudioWorklet: Add setOutputValueCallback

### PR DESCRIPTION
**Pull request by eddyc**
Add callback for reading values out from the outvalue opcode.

### CODE REVIEW

**Comment by kunstmusik** [comment]
Looks good but haven't tested. Any chance to get a test added to the demos and to have this implemented for ScriptProcessorNode?

**Comment by eddyc** [comment]
Will do

**Comment by kunstmusik** [comment]
@eddyc Any update on this?

**Comment by kunstmusik** [comment]
@eddyc The last commit had some .vscode files in it, could that be redone?  Also, is this all of the changes for the PR or are there any others planned?

**Comment by eddyc** [comment]
Sure, I'll close it for now. I need to do the SPN version but honestly
don't have time right now.

**Pull request closed without merging**
