### PR TITLE
add version of pow for the case kout[] = kx ^ ivalues[] 

### PR DESCRIPTION
**Pull request by gesellkammer**

### CODE REVIEW

**Comment by kunstmusik** [comment]
This looks good to me, are there updated manual pages already?

**Comment by gesellkammer** [comment]
I don't think that the manual page needs updating in this regard (although a good candidate for an update, since it does not say anything about the rates supported, arrays, etc.)

**Comment by gesellkammer** [comment]
Can this be merged?

**Comment by kunstmusik** [comment]
Yes, sorry, I have been a bit out of it the past few days with work. I'll merge now and add an issue to the manual repo that the page for ^ needs updating to reflect this change.

**Pull request merged**
