### PR TITLE
New Build Instructions

### PR DESCRIPTION
**Pull request by vlazzarini**
Starting new build instructions #717. Please contribute to it.

### CODE REVIEW

**Comment by vlazzarini** [comment]
@rorywalsh I think this is in good shape to merge. Could you review/approve it? I'll wait for the actions to complete then merge once it's approved.

**Comment by rorywalsh** [comment]
This looks good Victor, I wonder if git should be mentioned somewhere at the top of the page? I mention its use in the Windows instructions, so I guess it could be mentioned elsewhere too? Also, can I remove all but the custom cmake file in platform/windows? I think leaving those scripts there is a little confusing as they are no longer needed. I'm happy to make the changes, just want to get a heads up first.

**Comment by vlazzarini** [comment]
I think so, you can do both things.

**Review by rorywalsh — APPROVED** [review]
I think this is cleaner now with those files removed and build instructions for the 3 major OSs consolidated into a single file.

**Pull request merged**
