### PR TITLE
Move headers

### PR DESCRIPTION
**Pull request by bramtayl**
These headers are used in various utilities and plugins, so I thought I'd move them into the the public interface folder

For context, here's a quick audit of which plugins and utilities need these headers:

OpcodeBase.hpp: needed for
- ampmidid plugin
- doppler plugin
- ftsamplebank plugin
- mixer plugin
- signalflowgraph plugin

convolve.h: needed for
- cvanal utility

csGblMtx.h: needed for
- pmidi plugin

lpc.h: needed for
- lpc_export plugin
- lpc_import plugin
- lpanal utility

sdif.h: needed for:
- hetro utility
- sdif2ad utility

utilmain.h: needed for
- atsa utility
- cvanal utility
- dnoise utility
- envext utility
- extractor utility
- het_export utility
- hetro utility
- lpanal utlity
- mixer utility
- pv_export utility
- pv_import utility
- pvanal utility
- scale utility
- sndinfo utility
- srconv utility

### CODE REVIEW

**Comment by kunstmusik** [comment]
You might want to check with the developers about changes like this; these headers aren't meant to be public. The public include folder is for the API and libcsound.

**Comment by bramtayl** [comment]
> these headers aren't meant to be public

Hmm, presumably they shouldn't get used by plugins and utilities then?

**Comment by kunstmusik** [comment]
Not sure why would you assume that? 

These headers are useful for the specific plugins/utilities in the repo and may be shared internally due to historical development of the program, but we're not promoting nor supporting their use outside of this repo. If something should be made public we need to design for it rather than just make it public for convenience.

**Comment by vlazzarini** [comment]
no, they are only used internally. External plugins and hosts are not supposed to see these and do not needed them.

We're glad you are trying to lend a hand, but such changes are not needed or desirable. The system works, we have maintained this code base for twenty years, through changes etc and everything is kept in the right places and works as expected.

For any such we need two things:

a) a clear understanding of how Csound and libcsound works from the code structure point of view. 

b) a rationale for the changes.

Unless we have a) it is hard to have b) and if we don't have both, we're just wasting valuable effort that could be used elsewhere.

**Comment by bramtayl** [comment]
> a) a clear understanding of how Csound and libcsound works from the code structure point of view.

> b) a rationale for the changes.

I'm getting there! I appreciate the feedback!

**Comment by bramtayl** [comment]
> If something should be made public we need to design for it

Hmm, well, I think we should do that then. If plugins and utilities need the headers, presumably, they would be useful for users too? So users could write their own plugins and utilities?

**Comment by vlazzarini** [comment]
That's all good and we appreciate the help.

Just to clarify: the plugins and utilities maintained in the Csound repo may use non-public headers. The fact that a plugin use a certain header doesn't mean it is necessary public.

The public headers are those required by the API so that third-party hosts and plugins may be developed.

**Comment by vlazzarini** [comment]
> > If something should be made public we need to design for it
> 
> 
> 
> Hmm, well, I think we should do that then. If plugins and utilities need the headers, presumably, they would be useful for users too? So users could write their own plugins and utilities?

None of these are designed like that. All of the useful functionality is already provided in the public headers. Third-party plugins, utilities, hosts have access to them.

The non-public headers are just there because they may be shared by more than one source file in the repository.

Again, we've been working on this code for 20+ years. These things have not been arranged randomly, we have thought about them.

**Comment by bramtayl** [comment]
> Again, we've been working on this code for 20+ years

Just because the code is old doesn't mean there aren't things that can be improved? The book of revelation is like 2000 years old but that doesn't mean it's accurate.

**Comment by bramtayl** [comment]
For context, here's a quick audit of which plugins and utilities need these headers:

OpcodeBase.hpp: needed for
- ampmidid plugin
- doppler plugin
- ftsamplebank plugin
- mixer plugin
- signalflowgraph plugin

convolve.h: needed for
- cvanal utility

csGblMtx.h: needed for
- pmidi plugin

lpc.h: needed for
- lpc_export plugin
- lpc_import plugin
- lpanal utility

sdif.h: needed for:
- hetro utility
- sdif2ad utility

utilmain.h: needed for
- atsa utility
- cvanal utility
- dnoise utility
- envext utility
- extractor utility
- het_export utility
- hetro utility
- lpanal utlity
- mixer utility
- pv_export utility
- pv_import utility
- pvanal utility
- scale utility
- sndinfo utility
- srconv utility

**Comment by kunstmusik** [comment]
@bramtayl Did you not read anything we said about how these headers are not supposed to be public? Do you understand this point or will you continue to ignore this? These headers have no business being public as we are not interested to maintain them as such as part of a public SDK. 

Do you understand the difference between public and private headers and why you would want to reuse some internally to a project and what are the obligations when making something public between your project and others who use it? 

Of course we are always looking for improvements, but nothing in this PR is anything but a step backwards. It's essentially making headers public that we DO NOT want to make public.

**Comment by bramtayl** [comment]
I do understand the current distinction between the "internal" plugin/utility interface and the "external" user interface but I do think it would be a good long-term goal to make them consistent with each other.

I was just adding some extra context, that's all.

**Comment by kunstmusik** [comment]
What is inconsistent about having the public headers public and the private
ones private? Seems like you're saying we should be doing... the things
we've been doing all this time?

The extra context doesn't really tell us anything in this situation but
just reinforces they should remain private and the PR should have been
closed as it has been.

**Comment by gogins** [comment]
I think what Steven and Victor are saying is that along the way, and before
a number of plugins were moved out of the repo, some useful opcodes and
utilities were developed using these headers. So, these headers need to
stay in the repo to keep building these opcodes and utilities, but I think
the idea is that new extensions created outside of the repo, e.g. as front
ends or new plugin opcodes, should not use these headers, but only the
public headers.

I agree with the general idea here, but I'm not sure things were completely
thought through. There is indeed code in extensions outside the repo that
continues to use these headers. Some of this code is by me. I continue to
use OpcodeBase.hpp to develop new plugin opcodes because I find it easier
to use than the plugin opcode framework in the repo, and for a while I was
continuing to use some C++ code in the interfaces directory to build
CsoundAC.

This has created a certain amount of frustration and extra work for me.
What I have ended up doing is using Csound as a Git submodule in my
projects.  I can then build with any Csound headers that I need, locally.
In other words, I don't need to install the Csound package to build my
projects, because my repos install the Csound source code inside themselves.

In general, there are several ways of resolving the tension that you
understandably feel regarding external projects.

(1) Make Csound a Git submodule in the external project. This is quite
easy, and a lot of open source software manages external dependencies in
this way.

(2) Just appropriate the required headers and stick them into the external
project.

(3) Develop a rationale for adding something to the Csound API supported by
the public headers, and issue a pull request for those changes. This is
what you were trying to do, and if you still want to do this, I suggest
that you focus on one feature at a time that needs public support and build
a case for it. I think that most likely, most of the internal headers can
safely be ignored, but there might be some things that should in fact be
incorporated into the public API.

Don't hesitate to talk to me about this, either privately or on Discord,
especially if you have some concrete ideas about what needs to be included
(and why!).

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by bramtayl** [comment]
> What is inconsistent

Well, it's inconsistent that "internal" plugins have access to an extra "internal" interface, but "external" plugins written by users have don't.

I don't think I'm the only one who thinks this either: there's notes about this in the existing code:

```
#  error "Csound plugins and host applications should not include csoundCore.h"
#  error "Csound plugins and host applications should not include envvar.h"
#  error "Csound plugins and host applications should not include fftlib.h"
#  error "Csound plugins and host applications should not include lpred.h"
```

I see the inconsistency as a bad thing for a couple of reasons:

- It means we don't have the option of migrating "internal" plugins out of the main repo
- If a functionality is useful for an "internal" plugin, it's probably useful for an "external" one too
- It means that we can't link plugins to the csound library, and instead, have to recompile bits of the library for each plugin

**Comment by kunstmusik** [comment]
1. This is unrelated to this PR, which just moved private headers into the
public folder which shouldn't be.
2. There's some private-only things that are protected in the public
headers. There's no argument these should be cleaned up but again, that's
not what this PR was about and it's odd that you're bringing it up now.
This kind of inconsistency is good to fix. As far as I know @vlazzarini has
a plan for cleaning up the API headers to remove the private parts but he
can correct me if I've misunderstood what he had planned.
3. We recently had some internal functions moved to be made public for
reuse by plugins. It was a good PR that moved things in a way to follow the
API design. It wasn't just "move the header and make it public" without
regards to long-term support and design. If you identify something that
looks like a good candidate to add to the public API for reuse, please
follow the model done in https://github.com/csound/csound/pull/1715.
4. You need to review our comments on your other PR where we explained that
you don't link plugins to the csound library and only compile against
the header. If we need to add functionality to share we add it to the
CSOUND struct that gets passed in at runtime.

**Comment by kunstmusik** [comment]
@gogins Sorry to say but some of these headers were only ever used by you
and have caused problems over the years, leading to many lost hours
debugging memory issues/crashing related to plugins that you developed when
used in host languages and applications. I have suggested to Victor and
John we simply remove OpcodeBase.hpp and rewrite the opcodes based on them
but no one wants to spend their time on that when we can leave it for now
and focus on other work with higher priority. We also can't have
CsoundAC-specific code here. If CsoundAC needs something to be changed in
the public API that's fine and would be good to iron out, but if it's
really specific to CsoundAC why not add it to your project there?

**Comment by vlazzarini** [comment]
> > Again, we've been working on this code for 20+ years
> 
> 
> 
> Just because the code is old doesn't mean there aren't things that can be improved? The book of revelation is like 2000 years old but that doesn't mean it's accurate.

The code is not "old", it has been continuously improved along the years. What you proposed here is not an improvement as was explained, it is a backward step. I go back to my earlier comment: you don't understand the codebase and these changes cannot be done without such an understanding.

**Comment by vlazzarini** [comment]
> > What is inconsistent
> 
> 
> 
> Well, it's inconsistent that "internal" plugins have access to an extra "internal" interface, but "external" plugins written by users have don't.
> 
> 
> 
> I don't think I'm the only one who thinks this either: there's notes about this in the existing code:
> 
> 
> 
> ```
> 
> #  error "Csound plugins and host applications should not include csoundCore.h"
> 
> #  error "Csound plugins and host applications should not include envvar.h"
> 
> #  error "Csound plugins and host applications should not include fftlib.h"
> 
> #  error "Csound plugins and host applications should not include lpred.h"
> 
> ```
> 
> 
> 
> I see the inconsistency as a bad thing for a couple of reasons:
> 
> 
> 
> - It means we don't have the option of migrating "internal" plugins out of the main repo
> 
> - If a functionality is useful for an "internal" plugin, it's probably useful for an "external" one too
> 
> - It means that we can't link plugins to the csound library, and instead, have to recompile bits of the library for each plugin
> 
> 
> 
> 

Yes, you are the only one here thinking there are inconsistencies. We (in Csound 5) have agreed a design that lead to those notes being placed in the code. 

They only say that some headers should not be included directly because the API functions are declared elsewhere.

The fact that you keep insisting on plugins being linked to the library shows you do not understand how the code works. We don't need to recompile bits of code because plugins are not linked to the Csound library, this is an absurd statement.

We have migrated many opcodes to the plugins repository many years ago and have made some very definite decisions on what we should keep in the main repo. It is not true that we cannot migrate plugins out of the main code and that your PR fixes that.

It is not true that all headers used by plugins in this repo should be shared publicly because they are useful generally. One thing does not lead to another. 

Opcodes are plugins in this repo for a number of reasons, which include having external dependencies, having special licence conditions, being written in a language that is not C. Additionally, we have considered developing a version of Csound with more opcodes being placed in plugin libraries to make the code footprint customisable.

This PR is closed and we will stop wasting our time responding to misguided comments here.

**Comment by gogins** [comment]
It seems the plugins based on OpcodeBase.hpp are currently working.

I don't know why you would think I want CsoundAC related code in the Csound
base. I agreed long ago that it should not ever have been in the Csound
repository, and I have consistently worked to make it independent.  Just as
you suggest, I have been moving stuff that I really need into my own code.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by bramtayl** [comment]
> Did you not read anything

> we're just wasting valuable effort

> leading to many lost hours debugging memory issues/crashing

> we will stop wasting our time responding to misguided comments

FYI if you think this kind of unnecessarily hostile language is going to stop me from trying to contribute to the repository, you're wrong. But I'd suggest thinking about how to make an environment more welcoming to new contributors.

**Pull request closed without merging**
