### PR TITLE
small readme edit

### PR DESCRIPTION
**Pull request by vlazzarini**
Just a small readme edit to allow for github actions to run again.

### CODE REVIEW

**Review by stekyne — APPROVED** [review]

**Comment by vlazzarini** [comment]
@stekyne when you have a chance, could you take a look at unit test 58 (SndfileTests.testWriteSndfile) on Windows? It keeps failing, then I rerun it and it passes, I don't know what the issue is as I can't check the logs. Thanks!

**Comment by stekyne** [comment]
@vlazzarini it seems like heap corruption (Exit code 0xc0000374). I can't seem to reproduce it locally though.

**Comment by vlazzarini** [comment]
> @vlazzarini it seems like heap corruption (Exit code 0xc0000374). I can't seem to reproduce it locally though.

Ok, thanks. Interestingly the test produces an output (test.raw) because the following test depends on it. I am wondering whether the corruption is happening on exit? OTOH I run everything with a memory sanitizer and if there was something wrong regarding memory access I would have seen it here.

Maybe I should remove the line

```
csound->Free(csound, sfcbs);
```

because Csound would free this memory on destroy anyway.

**Comment by vlazzarini** [comment]
No, that didn't do anything. I'm at a loss.

**Comment by stekyne** [comment]
I can try and run a memory sanitzer on Windows and see if something is different.

**Comment by vlazzarini** [comment]
sounds good!

**Pull request merged**
