### PR TITLE
fixed seed initialization confusion in opcode beosc

### PR DESCRIPTION
**Pull request by gesellkammer**
This should fix the missing initialization of seeds marked in the last merge. @jpffitch: thanks for catching these errors!

### CODE REVIEW

**Comment by gesellkammer** [comment]
I don't see these warnings when I compile my own version. How should I set up cmake to enable all these warnings/errors?

**Comment by jpffitch** [comment]
Compile with options -W -Wall -Werror
That changes all warnings to errors and reports all warnings

**Comment by jpffitch** [comment]
Cannot see how to include these changes.  I have editted the simple ones into source but the long one a line 616 eludes me (on develop branch)

**Comment by gesellkammer** [comment]
I don't see what the problem is. The code you refer to adds a check for 
invalid size in a table.

**Comment by gesellkammer** [comment]
Everything seems merged, can this PR be closed?

**Comment by jpffitch** [comment]
Yes.

⁣Sent from TypeApp ​

**Pull request closed without merging**
