### PR TITLE
Add uniform default ladspa path

### PR DESCRIPTION
**Pull request by fsateler**
Replace the different checks in different files by a single fallback

Submitting as a PR since I don't know if it was intentional that csladspa had a mac specific path but dssi didn't

### CODE REVIEW

**Comment by vlazzarini** [comment]
The only issue with this, I think is that it will change how things currently work on Linux for csladspa. My reading of the code is that if there is no LADSPA_PATH set, then it will look for CSDs in the current directory. If this is thought to be a minor issue, I am happy to accept the patch.

**Comment by fsateler** [comment]
Ah interesting point. And that makes sense, given that it would be unusual to ship CSDs in /usr/lib/ladspa. But I guess a similar concern couldbe raised in mac?

**Comment by vlazzarini** [comment]
it could, however, it has been always the case since the first release that plugin CSDs go in the default place (the only choice really in that platform).

**Comment by kunstmusik** [comment]
@fsateler Is this pull request still in the works or can we close this?

**Comment by fsateler** [comment]
On 31 May 2015 at 22:32, Steven Yi <notifications@github.com> wrote:

> @fsateler <https://github.com/fsateler> Is this pull request still in the
> works or can we close this?
>

The thing remaining is more of a policy one. I certainly cannot advocate to
change csound's behavior just to make it easier for me as a downstream
packager.

Defaulting csladspa to read from /usr/lib/ladspa instead of . is weird but
not totally wrong IME: after all, most LADSPA hosts are GUIs and therefore
either need LADSPA_PATH set or will have . == ~ , which is not quite usable
either. This makes me think it is not likely people expect csladspa to read
from the current directory. But then I may just be lacking imagination.


-- 

Saludos,
Felipe Sateler

**Comment by fsateler** [comment]
I'm not pushing this further. I'd appreciate if a change like this is made, but its not the end of the world either, I can patch csound downstream.

**Pull request closed without merging**
