### PR TITLE
WIP: Public libs

### PR DESCRIPTION
**Pull request by bramtayl**
Keep a separate list for public, as opposed to private, dependencies.

Waiting for #1768

### CODE REVIEW

**Comment by hlolli** [comment]
it looks ok to me these changes, but you should fix the merge conflict and try to squash your commits, and maybe give conventional commit messages a try: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by bramtayl** [comment]
Sure, I'll try that in contentail commit messages in the future. Sorry for the multiple commits; they came from splitting up a PR into a bunch of smaller commits. The first commit in the chain is https://github.com/csound/csound/pull/1760, maybe start there?

**Comment by stekyne** [comment]
I think that's part of the merge conflict problem though. You're editing the same file and same flags even in multiple PRs. I think you need to condense all those changes to one reasonably sized PR otherwise it's hard to see how all these changes will mix together.

**Comment by bramtayl** [comment]
I'll just merge this into #1739

**Pull request closed without merging**
