### PR TITLE
Bump cmake minimum version to 2.8.12

### PR DESCRIPTION
**Pull request by fsateler**
This allows:
1. Using PRIVATE linking instead of setting LINK_INTERFACE_LIBRARIES to empty.
2. Drop the add_compiler_flags function, as cmake now has target_compile_options
3. Use target_include_directories in many places. This prevents conflicts when eg, several projects may ship a `config.h` in their public headers.

I tested a few configurations on linux. Testing on OSX and Windows appreciated, as I cannot test that.

The only distributions I know of that do not have cmake >= 2.8.12 are debian Wheezy (that is, not the current release but the previous one, already end-of-lifed, now supported by the LTS team), and ubuntu Precise (the previous LTS, due to be end-of-lifed on april 2017).

### CODE REVIEW

**Comment by fsateler** [comment]
Heh, the travis build is on ubuntu precise so it didn't have the cmake version. I will test the trusty ci env now.

**Comment by kunstmusik** [comment]
@fsateler I tried building the update-cmake branch here on Windows 10 with mingw64 and msys2.  The build was successful here.  

The changes look very beneficial.  Are there any further changes you have or is this okay to merge?

**Comment by fsateler** [comment]
I have a single change remaining (change the last commit to remove instead of comment the lines).

Also, testing on OSX would be good as well.

Other than that it is good from my POV.

**Comment by kunstmusik** [comment]
I tested update-cmake here on OSX 10.11.  I had a weird quirk where I had to regenerate with Cmake a second time before it compiled; not sure what the problem was, but seems okay enough to me.  Let me know when the last commit is ready and I will merge it.

**Comment by jpffitch** [comment]
Do I read that that those of us using Whezzy are being abandoned?  There are reasons not to upgrade my firewall/mail server, like changes to /etc/init.d

**Comment by kunstmusik** [comment]
What version of CMake is available on Wheezy?

**Comment by fsateler** [comment]
@jpffitch that would be a side effect, yes. Maybe we can wait a bit more before bumping the required version. But I encourage you to migrate your server to jessie, you will have to do so eventually anyway (also, you can still use sysvinit in jessie if you don't like systemd. The prospects for the next release are not so good as nobody is maintaining sysvinit though).

@kunstmusik The version in wheezy is 2.8.9, and 2.8.11 is available in wheezy backports.

**Comment by fsateler** [comment]
I applied the travis change directly to develop, and rebased this branch on top. However, maybe this change can be delayed for a while to allow building in wheezy.

**Comment by stekyne** [comment]
Any change on this work and maybe deliver it? Looks like a good idea and maybe is relevant now that we're making changes to the cmake files for the MSVC build.

**Comment by fsateler** [comment]
> Any change on this work and maybe deliver it?

That would depend on the need to continue to build on debian wheezy, which lacks the required cmake version. If that need is gone, then I can certainly update this pr and fix the conflicts.

**Comment by jpffitch** [comment]
I still have whezzy and upgrading is hard -- critical infrastructure computer.

⁣Sent from TypeApp ​

**Comment by fsateler** [comment]
> I still have whezzy and upgrading is hard -- critical infrastructure computer.

Maybe it is feasible to create a (debian sid) chroot for building csound in that computer?

**Comment by fsateler** [comment]
Sorry pressed the wrong button

**Comment by fsateler** [comment]
I have rebased the patches against current develop. I also did some simplifications by using the PUBLIC/PRIVATE include dirs.

Testing on non-linux platforms appreciated.

**Comment by fsateler** [comment]
I have rebased the branch. 

I have no idea why the appveyor build failed. AFAICT there are no compiler errors...

**Comment by stekyne** [comment]
CMake Error at Opcodes/CMakeLists.txt:336 (target_compiler_definitions):
  Unknown CMake command "target_compiler_definitions".
-- Configuring incomplete, errors occurred!

I wonder what Cmake version is there. Thought it was pretty much latest.

**Comment by fsateler** [comment]
Ah, I didn't see that. The function should be target_compile_definitions (no r). I wonder why it didn't fail for me locally...

**Comment by fsateler** [comment]
Failure now seems unrelated to these changes, unless I'm missing something...?

```
csoundvst_main.obj : error LNK2019: unresolved external symbol RunCsoundVST referenced in function main [C:\projects\csound\msvc\csound-vs\frontends\CsoundVST\csoundvstmain.vcxproj]
   127>C:\projects\csound\msvc\csound-vs\Release\csoundvstmain.exe : fatal error LNK1120: 1 unresolved externals [C:\projects\csound\msvc\csound-vs\frontends\CsoundVST\csoundvstmain.vcxproj]
   127>Done Building Project "C:\projects\csound\msvc\csound-vs\frontends\CsoundVST\csoundvstmain.vcxproj" (default targets) -- FAILED.
```

Is the build of that symbol conditional on something?

/cc @gogins

**Comment by fsateler** [comment]
I think I see the error. In rebasing, I undid parts of 98baca0 . Lets see if by redoing those changes fixes the build.

**Comment by fsateler** [comment]
CI is passing now 😄

**Comment by stekyne** [comment]
Is there anything preventing the merge still so? Would be nice to have these changes.

**Comment by kunstmusik** [comment]
This looks like a nice change to have.  I think most of us are using Cmake >= 2.8.12.  

@jpffitch  - Are you still affected by this (using Wheezy)?

**Comment by jpffitch** [comment]
Using a slightly broken Jessie now which gives 3.0.2;. version 3.5.2 on SuSE

⁣Sent from TypeApp ​

**Comment by kunstmusik** [comment]
Thanks John and Felipe, I've gone ahead and merged.

**Pull request merged**
