### PR TITLE
New array opcodes, bandwidth enhanced oscillator

### PR DESCRIPTION
**Pull request by gesellkammer**
# beosc

Beosc is a set of opcodes for bandwidth enhanced additive synthesis. It is based on the supercollider port of loris. It does not depend on any external library and only implements resynthesis. This is done through two opcodes

* `beosc`: bandwidth-enhanced oscillator, a linearly interpolated oscillator amplitude modulated by noise.
* `beadsynt`: bandwidth-enhanced additive synthesis. Based on csound's adsynt2, adds a bandwidth parameter per oscillator, the noise modulation can have either a uniform or gaussian distribution, with optional frequency interpolation and wavetable lookup interpolation. 
* `tabrowlin`: assuming a 2d (flattened) function table containing multiple rows of sampled streams (for instance, the amplitudes of a set of oscilators), extract one row of that data
with a possible linear interpolation between adjacent rows. 

# emugens

## New opcodes

* `arrayreshape`: given a 1D or 2D array, change the shape of the array. Useful to convert a 1D flat array (possibly copyied from a table) to a 2D array
* `arrayslice`: copy a slice of an array or a table, with optional start, end, and step values. Overlaps with slicearray and could be disposed of if slicearray would add a `step` parameter and the ability to copy from a table also.
* `ftslice`: copy a portion of a table to another table, with optional start, end, and step values
* `arrayprint`: print a (possibly multidimensional) array to stdout
* `arrayview`, `arrayviewend`: create a 'view' on a ftable or another array, possibly indicating start and end indices. This is just a pointer to the original memory, so nothing is copyied.

## Additions

* `linlin`: accepts arrays in the form of `kOut[] linlin kIn[], klow, khigh`, or `kOut[] linlin kx, kLow[], kHigh[]` 
* `cmp`: accepts arrays and 'in between' comparison: 
`kOut[] cmp klow, "<", kIn[], "<=", khigh`
* `bpf`: accepts any number of pairs

### CODE REVIEW

**Comment by kunstmusik** [comment]
Something is very wrong with this PR as it notes 3076 file changes (mostly from https://github.com/csound/csound/pull/846/commits/997f652aa14605aac145de40b4b59776d5381816 I believe).  I'd ask to rebase the changes based upon latest from develop so only the relevant code changes are in the PR.

**Comment by gesellkammer** [comment]
I'm not that familiar with git, what should I do?

**Comment by kunstmusik** [comment]
I'm not sure exactly what's best here either, since you have commits that are just merges within the history.  Keeping a copy of your existing git repo locally, you might try to delete your repo on GitHub, re-fork, then create a branch for the changes.  In the branch, you could then copy just the differences from the old repo and make one large commit, or cherry pick commits from one repo to the other.  

There might be another way to delete commits and push those deletions to your fork on GitHub to backtrack the work, then rebase to latest from develop in the main Csound GitHub project, then reapply commits, but I'm not sure that's easier/better.

@fsateler is pretty knowledgeable about Git practices, any thoughts Felipe?

**Comment by fsateler** [comment]
This PR has a lot of anomalies. I'd start afresh in a new branch. AFAICT, the relevant changes are all in new files, plus cmake integration. The rest appears to be noise caused by some other tool (eg, I see a lot of unrelated code formatting changes and permission changes), and some unrelated removals (examples/html).  @gesellkammer , I recommend the following:

```sh
# First setup the repo
git clone git@github.gesellkammer/csound.git 
cd csound
git remote add upstream https://github.com/csound/csound.git
git remote update
# create a new branch for your work, but starting fresh
git checkout -b beosc upstream/develop
# copy the new opcode files, edit cmake integration as appropriate then commit
# Finally push your changes to a new branch
git push -u origin beosc
# and create a new PR in the web interface
```

Sometimes it is easier to start afresh than fix the current branch :wink:

**Comment by gesellkammer** [comment]
Thanks!! That worked perfectly.

**Comment by kunstmusik** [comment]
Closing this PR as PR #847 was created.

**Pull request closed without merging**
