### PR TITLE
 better rendering of console, XHTML aware

### PR DESCRIPTION
**Pull request by hfmanson**
replace innerHTML with createTextNode, createElementNS and textNode. 
UpdateStatus: 'keep' parameter defaults to true
minimal demo's in html/xml using div console

### CODE REVIEW

**Comment by kunstmusik** [comment]
@hfmanson I think the changes look good, but at the same time the new version of WebAudio Csound will likely move away from csound.js (or at least, require a rewritten version to work with the revised core WebAudio Csound API) and encourage direct use of the core API.  

@vlazzarini I think we should simplify to supporting just the core API now and phase out use of csound.js as I think almost no one has used the PNaCl version of Csound at this point.  I think the examples should be easy to migrate from csound.js to the new API.  Thoughts?

**Comment by hfmanson** [comment]
is there a branch where the new version of WebAudio Csound is developed on?

**Comment by kunstmusik** [comment]
Yes it is the feature/webaudio-csound branch:

https://github.com/csound/csound/tree/feature/webaudio-csound

The work for this version is done in the wasm folder and has significant changes using a different compiler, updated API, etc.  There's some documentation there but @hlolli and I are going to put together a separate website (https://github.com/csound/webaudio/) that will eventually be served at csound.com/webaudio that will have installation information, API documentation, examples, tutorials, etc.

**Comment by vlazzarini** [comment]
happy to phase out csound.js in this upcoming review. Just removing it and the examples using should be ok.

**Comment by kunstmusik** [comment]
Thanks @vlazzarini!

FYI: I went ahead and merged; we'll see about updating and incorporating the old examples into the new webaudio sub-site for csound.com. I'll also make a note in the ChangeLog that csound.js is going away.

**Pull request merged**
