### PR TITLE
Externals as plugins

### PR DESCRIPTION
**Pull request by vlazzarini**
This is work-in-progress to develop a build with externals as plugins (https://github.com/csound/csound/issues/1865)

It needs the following to be continued
1. PRs 1844, 1848, 1852, 1859 need to be completed and merged.
2. A review of code locations and files in Opcodes so that plugin modules can be better organised.
3. Complete the CMake restructuring to allow the BUILD_PLUGINS option to build all externals as plugins.

### CODE REVIEW

**Comment by vlazzarini** [comment]
This is complete now. All external opcodes can be built as plugins.

**Review by stekyne — APPROVED** [review]
CMake parts look fine to me

**Comment by vlazzarini** [comment]
@stekyne thanks for the review. I might wait until the CI is fixed before merging.

**Comment by stekyne** [comment]
@vlazzarini i fixed develop last night. You can rebase and it'll work

**Comment by vlazzarini** [comment]
Excellent! Thanks

**Pull request merged**
