### PR TITLE
Swift 4 update, added Accelerate to linked frameworks in examples projects

### PR DESCRIPTION
**Pull request by nikhilsinghmus**
Minor update to Swift 4 and Xcode's newest recommended settings, and adding Accelerate to the linked frameworks in the example projects so that users don't have to.

### CODE REVIEW

**Comment by kunstmusik** [comment]
@vlazzarini Perhaps an updated release?  Thinking we may get further questions about Accelerate otherwise.

**Comment by vlazzarini** [comment]
Ok, no need for a new build, just re-packaging is that right?

**Comment by kunstmusik** [comment]
Yes, I think that's right, libcsound.a and all that should be just fine.

**Comment by vlazzarini** [comment]
Ok done.

**Pull request merged**
