### PR TITLE
Bug in hdf5read

### PR DESCRIPTION
**Pull request by eddyc**
Editing the input argument names directly resulted in a bug where a second instance of the hd5read opcode would have inaccurate input argument names.

### CODE REVIEW

**Comment by jpffitch** [comment]
This undoes recent canges to Victo;s code so he should comment
==John

**Comment by jpffitch** [comment]
This undoes a recent change from victor so he should comment

**Comment by eddyc** [comment]
If it does it's a mistake on my part, but I think the commit where I changed it is overwritten with Victor's other solution, if you look at the files changed for this pull request there is only HDF5IO.h and HDF5IO.c.

**Comment by jpffitch** [comment]
I would merge if I knew how as long as plugins.h is not changed

**Comment by vlazzarini** [comment]
I think you should close this pull request and try another one with no change to plugins.h

**Comment by jpffitch** [comment]
Merged code in HDF

**Pull request closed without merging**
