### PR TITLE
lufs opcode, #1347

### PR DESCRIPTION
**Pull request by gleb812**
lufs opcode for loudness level calculation

### CODE REVIEW

**Comment by kunstmusik** [comment]
@gleb812 This looks like it has commits that were already committed to csound separately. To get a clean PR, I think the simplest thing might be to:

1. Pull the latest from csound repository's develop branch to your fork
2. Make a branch from develop
3. Re-add the lufs change
4. Create a new PR

Also, rather than use LINKAGE for this to be an opcode library, you might instead add this to core as there are no dependencies. You would have to add entries to Engine/entry1.c and include lufs.h and update CMakeLists.txt to add the lufs.c file to the source list. There is an additional place to add source for the Android build (Android/CsoundAndroid/jni/Android.mk).

**Comment by gleb812** [comment]
Ah, yes. Will do it soon

**Comment by vlazzarini** [comment]
I agree with Steven, it can just be an internal opcode.

Gleb, if it's easier you can add this as a plugin and we can make it an internal opcode ourselves. Up to you.

**Comment by gleb812** [comment]
Good. Then I will try to go with the plugin, since I can't get rid of those errors:
In file included from /home/gleb/src/csound/Engine/entry1.c:24:
/home/gleb/src/csound/Engine/entry1.c:1213:17: error: ‘LUFS’ undeclared here (not in a function)
 1213 |    {"lufs.a", S(LUFS), 0, 3, "kkk", "a",
      |                 ^~~~
/home/gleb/src/csound/./H/entry1.h:62:24: note: in definition of macro ‘S’
   62 | #define S(x)    sizeof(x)
      |                        ^
/home/gleb/src/csound/Engine/entry1.c:1215:18: error: ‘LUFS2’ undeclared here (not in a function)
 1215 |    {"lufs.aa", S(LUFS2), 0, 3, "kkk", "aa",
      |                  ^~~~~
/home/gleb/src/csound/./H/entry1.h:62:24: note: in definition of macro ‘S’
   62 | #define S(x)    sizeof(x)
      |                        ^
make[2]: *** [CMakeFiles/csound64.dir/build.make:158: CMakeFiles/csound64.dir/Engine/entry1.c.o] Error 1
make[2]: Leaving directory '/home/gleb/src/csound/build'
make[1]: *** [CMakeFiles/Makefile2:707: CMakeFiles/csound64.dir/all] Error 2
make[1]: Leaving directory '/home/gleb/src/csound/build'
make: *** [Makefile:186: all] Error 2

**Comment by vlazzarini** [comment]
Hi Gleb,

the LUFS etc structures need to go in a header file in ./H and you need to add that header as an included file in entry1.h 

Best thing is to find a suitable file in ./OOPs  to place your code (functions) and the structs go in the corresponding header file in ./H 

This way you don't need to add anything to CMakeLists.txt and it's all there.

The only thing you will need to do extra is to declare your functions in entry.h, so that entry.c can see them.

**Comment by gleb812** [comment]
ah.. I see now. Thanks for the advice. I made a new request (for plugin).

**Comment by vlazzarini** [comment]
ok, I'm closing this.

**Pull request closed without merging**
