### PR TITLE
fix: using boolean tokens in boolean expressions

### PR DESCRIPTION
**Pull request by hlolli**
this fixes the segfault reported in this ticket https://github.com/csound/csound/issues/1669 as well as segfaults which I discovered for if-else statements as well.

### CODE REVIEW

**Comment by vlazzarini** [comment]
I've checked this and the boolean test is not passing correctly. It may need a good deal of work to get it right

**Review by vlazzarini — APPROVED** [review]
all looks good now, test is passing and we have booleans working in control flow.

**Comment by hlolli** [comment]
thanks for getting it to work, I look forward making use of for the purposes of [less cognitive load](https://github.com/zakirullin/cognitive-load)

**Comment by vlazzarini** [comment]
absolutely. Actually it was working when you placed the PR but it stopped working with the changes we had made later on. All I had to do was to fix these to accept booleans.

**Pull request merged**
