### PR TITLE
Squinewave opcode

### PR DESCRIPTION
**Pull request by ostinato**

### CODE REVIEW

**Comment by kunstmusik** [comment]
@ostinato This failed to build for Windows and Linux. It looks to me that the Opcodes/squinewave.c file needs to be added to the libcsound source file list (CMakeLists.txt in the main source folder, around line 821 or so).  Could you update the Pull Request with the change to CMakeLists.txt?

**Comment by kunstmusik** [comment]
@ostinato I was about to merge this PR but saw that there were updates. Is this PR now okay to merge?  (And you may need to do a PR or file an issue with the squinewave docs to the manual repo.)

**Comment by ostinato** [comment]
1 sec, that stupid Sourcetree thing always creates commit instead of pull request. 
It's quite vexing

**Comment by ostinato** [comment]
Now, thanks!
I know about the manual, another cumbersome process.

It used to be simple to add something to Csound... (tho I guess it's easier for those who actually contribute now)

**Comment by kunstmusik** [comment]
Merged this in. Once I did a change to set --std=gnu99 (c99 didn't do it alone), I saw that there was a problem with min/max; changing to fmin/fmax did the job for Linux.  Compiles locally with Ubuntu and Windows (MinGW and Visual Studio).  Should hopefully be good to go, thanks!

**Pull request merged**
