### PR TITLE
Some Travis updates

### PR DESCRIPTION
**Pull request by fsateler**
Unfortunately cmake does not seem to pick up eigen. Maybe it's too old version?

### CODE REVIEW

**Comment by fsateler** [comment]
This makes tests a lot faster as they use the container-based images.

Re eigen, this would not be a regression, as it was not being installed previously

**Comment by kunstmusik** [comment]
@fsateler libeigen3-dev is listed twice in the change, is this intentional?

**Comment by fsateler** [comment]
Ehm, no its not, I somehow missed that it was already there. Force pushed a fixed commit.

**Comment by kunstmusik** [comment]
@fsateler Is this commit supposed to show up in this PR?  (I'm not seeing an update.)

**Comment by fsateler** [comment]
Sorry, now it is.

**Comment by kunstmusik** [comment]
Looks good to me and the previous test passed Travis, so I'll merge now. Thanks!

**Pull request merged**
