### PR TITLE
Add a clear events function

### PR DESCRIPTION
**Pull request by bramtayl**
This is useful in case you want to clear previous events and start fresh

### CODE REVIEW

**Comment by kunstmusik** [comment]
Not sure this is doing as advertised? Seems to only clear pending messages for Perf Threads and not score events that are csound's scheduler? Or am I missing something?

**Comment by bramtayl** [comment]
I'm most likely missing something, this was a bit of a stab in the dark

**Comment by bramtayl** [comment]
There isn't a way to do this already, is there?

**Comment by Oeyvind** [comment]
I think you can use turnoff3 for this (?). To delete instr events  "in the
queue of scheduled events" (https://csound.com/docs/manual/turnoff3.html).

fre. 7. juli 2023 kl. 17:06 skrev bramtayl ***@***.***>:

**Comment by bramtayl** [comment]
I don't think that does quite what I want it to do. I want basically a new performance thread without having to restart the whole csound session

**Comment by bramtayl** [comment]
But it works as a workaround for now. Would be inconvenient if I had a ton of instruments but I only have a few

**Pull request closed without merging**
